---
version: '3.8'
services:
  movies:
    image: rahulkatakam/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: rahulkatakam/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: rahulkatakam/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: rahulkatakam/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

